### PR TITLE
Added appveyor.yml

### PR DESCRIPTION
**Pull request by brynpickering**
This is just a conda-smithy rerender of the main repository, with windows 'skip' removed.

### CODE REVIEW

**Comment by scopatz** [comment]
Hi thanks for putting this in, but I think it needs a bld.bat file that implements the coin install instructions.

**Comment by scopatz** [comment]
I am not a windows Dev and have never built coin on windows, but can help with general questions

**Comment by brynpickering** [comment]
Yep, I've been working on a local version with a bld.bat to install a bintray windows binary of it. However, the windows binary has a bug which I'll need to raise an issue on at the main Cbc repo!

**Comment by scopatz** [comment]
Ahh excellent!

**Pull request closed without merging**
