### PR TITLE
Rebuild with parallel OpenBLAS

### PR DESCRIPTION
**Pull request by jakirkham**
Bump build number and rebuild with the parallel OpenBLAS.

### CODE REVIEW

**Comment by jakirkham** [comment]
Weird. I thought AppVeyor was disabled for this. We should fix up the BLAS stuff more than what has been done here, but I just want to get a fresh build that is ok first.

**Comment by scopatz** [comment]
Yeah, I thought appveyor was disabled too.  A fresh build sounds fine to me, but it is also failing on circle.

**Comment by jakirkham** [comment]
Yep, saw that. There was a build timeout. Going to hold on restarting it until we can get SciPy rebuilt.

**Comment by jakirkham** [comment]
SciPy is not done yet, but it seems to be progressing nicely. So giving this another go.

Given we were seeing [timeouts](https://circleci.com/gh/conda-forge/coincbc-feedstock/2), it seems OpenBLAS may be using an unreasonable number of threads (as that is the only thing that has changed). As it was building fine when OpenBLAS had used 1 thread previously, it makes sense to fix the number of threads OpenBLAS uses to 1. Thus I have made this change to the build script. As this is irrelevant for the testing section currently, I have not added it there. Let's see how this does.

**Comment by jakirkham** [comment]
CircleCI passed this time. Seems to suggest restricting the number cores fixed the issue. Travis CI was already passing. So don't expect that to change.

**Comment by scopatz** [comment]
Great, I'll merge when travis passes then!

**Comment by jakirkham** [comment]
Thanks. Sorry for the trouble.

**Comment by scopatz** [comment]
Not a problem!  This is far from my biggest coin problem in the past week :)

**Comment by jakirkham** [comment]
Alright, appears it is passing now. Feel free to take it away.

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
