### PR TITLE
remove gcc from build

### PR DESCRIPTION
**Pull request by scopatz**
Here goes nothing.

### CODE REVIEW

**Comment by jakirkham** [comment]
The error makes it seem like it requires Fortran somehow. However, the [codebase](https://github.com/coapp-packages/coin-cbc) and [docs](https://projects.coin-or.org/Cbc) suggest otherwise.

**Comment by scopatz** [comment]
For what it is worth, I don't fully trust coin about its needs.

**Comment by jakirkham** [comment]
Let's assume it needs Fortran. I'd take a look at these PRs and try to do something similar here.
- https://github.com/conda-forge/scipy-feedstock/pull/2
- https://github.com/conda-forge/scipy-feedstock/pull/3

This should hopefully get rid of the `libgcc` dependency. Though it gets a bit messy. Unfortunately I can't dig into this too much near term, but hopefully that gives you enough to get started. I'll try to check back in near the end of the week to see where we stand.

**Comment by scopatz** [comment]
This is not possible due to the need for a fortran compiler.

**Comment by jakirkham** [comment]
There is a way to do it so that one only depends on `libgfortran` and not `libgcc`, but it is not easy. If you are interested, we can discuss further.

**Comment by scopatz** [comment]
I am not interested personally. I think this is fine for my needs.  But PRs welcome :)

**Comment by jakirkham** [comment]
Sorry, I simply lack time or interest in this. So am unlikely to submit a PR. Happy to discuss if it does become an issue though.

**Comment by isuruf** [comment]
Btw, openblas provides lapack. `lapack` package is not optimized like `openblas` and therefore slower than `openblas`

**Pull request closed without merging**
